version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SEED: 123e4567-e89b-42d3-a456-556642440000
    volumes:
      - ./:/home/app
      - node_modules_webapp:/home/app/node_modules

volumes:
  node_modules_webapp:
